improve pdf_search

diff --git a/.local/bin/pdf_search b/.local/bin/pdf_search
--- a/.local/bin/pdf_search
+++ b/.local/bin/pdf_search
@@ -1,17 +1,18 @@
 #!/bin/sh
+# Requirements:
+# - fd
+# - zathura
 
-# Get all the PDFs in the home directory.
-FILES=$(fd -e pdf '' $HOME)
+# Exits the script if any of the commands fails.
+set -e
 
-# Filter out the beginning of the paths and the file extension
-# and pass those files to rofi for the user to select from.
-FILE_INDEX=$(echo "$FILES" \
-  | sed -e "s#$HOME/\(.*\)\.pdf#\1#gi" \
-  | dmenu -i -l 5 -p " PDF")
+# Filter out the home from the list of files 
+# and pass those files to dmenu for the user to select from.
+FILE_INDEX=$(
+  fd -e pdf '' $HOME \
+  | sed -e "s@$HOME/@@gi" \
+  | dmenu -i -l 5 -p " PDF"
+)
 
 # If the user selected a file, open it up!
-case $FILE_INDEX in
-  -1) ;;
-  "") ;;
-  *) zathura "$(echo "$FILES" | sed -n ${FILE_INDEX}p)" ;;
-esac
+"${READER:-zathura}" "${HOME}/$FILE_INDEX"
